{{- if and (not .Values.downstream.existingSecret) (or .Values.config.mqtt.password .Values.config.rest.token) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clock-server.downstreamSecretName" . }}
  labels:
    {{- include "clock-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.downstream.secretKeys.mqttPassword }}: {{ .Values.config.mqtt.password | quote }}
  {{ .Values.downstream.secretKeys.restToken }}: {{ .Values.config.rest.token | quote }}
{{- end }}
